### PR TITLE
Hw24

### PR DESCRIPTION
**Pull request by iibrahimsv**
Homework Checking Team,

Homework 24 is ready for review. Please advise 👍🏽 

Best Wishes

-Abdi Ibrahim

### CODE REVIEW

**Comment by Berichicko** [comment]
Hello

Homework  24 is cheeked! 

I left comments on your code!


**Good work!**  🔥


**Your grade: 85**  ✊


💖Best wishes, the team HW (Alex)!💖





I refactored your code in the class:


```
class BasePage
class HomePage
class LoginPage

class BaseTest
LoginTests
```

_I have added files to the project:_

selenium-server-4.6.0.jar

geckodriver.exe


image

**Comment by iibrahimsv** [comment]
Thank you for the feedback @Berichicko As a MacOS user test ran smoothly. Should I still import these files?

**Comment by Berichicko** [comment]
> Thank you for the feedback @Berichicko As a MacOS user test ran smoothly. Should I still import these files?

No, don’t! Thank you!

**Comment by iibrahimsv** [comment]
Sounds great. Thank you again. Will revise, make changes, and push.

**Pull request closed without merging**
